<template>
  <div v-if="show" class="floating-popup ot-note-popup" :class="{ expanded: isExpanded }" :style="!isExpanded ? { top: pos.y + 'px', left: pos.x + 'px' } : {}">
    <div class="popup-header ot-header" @mousedown="startDrag"><div class="popup-title">{{ otNumber }}</div><div class="popup-controls"><span class="material-icons" @click.stop="toggleExpand">{{ isExpanded ? 'fullscreen_exit' : 'fullscreen' }}</span><span class="material-icons" @click="$emit('close')">close</span></div></div>
    <div class="popup-body ot-body">
      <div class="ot-info"><div><label>Tarea</label><input value="DOM - ALTAS HFC" disabled /></div><div><label>Domicilio</label><input value="DE LUJAN NTRA SRA 1525" disabled /></div><div><label>Clase Ot</label><input value="New Connect" disabled /></div><div><label>Tecnico Cierre</label><input value="23TID240" disabled /></div><div><label>Nro Cliente</label><input value="8.10081755121E15" disabled /></div></div>
      <div class="ot-tabs"><button v-for="tab in tabs" :key="tab.id" :class="{ active: activeTab === tab.id }" @click="activeTab = tab.id">{{ tab.label }}</button></div>
      <section class="tab-box">
        <div v-show="activeTab === 'actividades'"><h4>Actividades Originales</h4><SimpleTable :columns="actividadesCols" :rows="actividades" /></div>
        <div v-show="activeTab === 'base'"><h4>Base Instalada</h4><SimpleTable :columns="baseCols" :rows="baseInstalada" empty="No hay base instalada para mostrar." /></div>
        <div v-show="activeTab === 'historial'"><div class="section-title"><h4>Historial del domicilio</h4><button class="btn-cyan" @click="exportHistorial">EXPORTAR HISTORIAL COMPLETO</button></div><div class="table-wrap"><table class="fm-grid"><thead><tr><th></th><th>NRO OT</th><th>FECHA CREACION OT</th><th>FECHA CIERRE</th><th>NRO ACTA</th><th>ESTADO ACTA</th><th>EMPRESA CONTRATISTA</th><th>OT RED</th></tr></thead><tbody><tr v-for="hist in historial" :key="hist.ot"><td><button class="arrow-btn" @click="openHistorial(hist)"><span class="material-icons">arrow_right</span></button></td><td class="ot-link">{{ hist.ot }}</td><td>{{ hist.creacion }}</td><td>{{ hist.cierre }}</td><td>{{ hist.acta }}</td><td>{{ hist.estado }}</td><td>{{ hist.contra }}</td><td>{{ hist.red }}</td></tr></tbody></table></div></div>
        <div v-show="activeTab === 'materiales'"><div class="section-title"><h4>Materiales</h4><button class="btn-cyan" @click="consultarMateriales">CONSULTAR MATERIALES</button></div><SimpleTable :columns="materialCols" :rows="materiales" empty="No se encontraron materiales." /></div>
        <div v-show="activeTab === 'siniestros'" class="siniestros-box"><div><label>Nro EHS</label><input v-model="siniestro.nroEhs" /></div><div><label>Nro OI</label><input v-model="siniestro.nroOi" /></div><div class="siniestros-actions"><button class="btn-cyan-outline" @click="limpiarSiniestro">CANCELAR</button><button class="btn-cyan" @click="guardarSiniestro">ACEPTAR</button></div></div>
      </section>
      <section class="resultantes"><h4>Actividades Resultantes</h4><SimpleTable :columns="resultCols" :rows="resultantes" selectable /></section>
    </div>
    <div class="popup-actions"><button class="btn-cyan" @click="showValidateConfirm = true">VALIDAR ACTIVIDADES</button><button class="btn-cyan" @click="showSaveAlert = true">GUARDAR CAMBIOS</button></div>
    <SubgrillaHistorialPopup :show="showSubgrilla" :data="selectedHistorial" @close="showSubgrilla = false" />
    <FmConfirmDialog :show="showValidateConfirm" message="¿Confirma que desea validar las actividades?" @cancel="showValidateConfirm = false" @confirm="confirmValidate" />
    <FmAlertDialog :show="showMaterialsAlert" message="No se encontraron materiales." @close="showMaterialsAlert = false" />
    <FmAlertDialog :show="showSaveAlert" title="Cambios guardados" message="Los cambios fueron guardados correctamente." @close="showSaveAlert = false" />
  </div>
</template>

<script setup>
import { defineComponent, h, ref, watch } from 'vue'
import SubgrillaHistorialPopup from '../../popup/SubgrillaHistorialPopup.vue'
import FmConfirmDialog from '../../shared/FmConfirmDialog.vue'
import FmAlertDialog from '../../shared/FmAlertDialog.vue'
import { downloadExcel } from '../../../utils/excelExport.js'

const SimpleTable = defineComponent({ props: { columns: Array, rows: Array, empty: String, selectable: Boolean }, setup(props) { const toggleAll = (event) => props.rows.forEach((row) => { row.selected = event.target.checked }); const toggleRow = (row, event) => { row.selected = event.target.checked }; return () => h('div', { class: 'table-wrap' }, [h('table', { class: 'fm-grid' }, [h('thead', [h('tr', [(props.selectable ? h('th', { class: 'check-col' }, [h('input', { type: 'checkbox', checked: props.rows.length > 0 && props.rows.every((row) => row.selected), onChange: toggleAll })]) : null), ...props.columns.map(c => h('th', c.label))])]), h('tbody', props.rows.length ? props.rows.map((r, i) => h('tr', { key: i, class: r.selected ? 'selected' : '' }, [(props.selectable ? h('td', { class: 'check-col' }, [h('input', { type: 'checkbox', checked: !!r.selected, onChange: (event) => toggleRow(r, event) })]) : null), ...props.columns.map(c => h('td', r[c.field] || ''))])) : [h('tr', [h('td', { class: 'empty-row', colspan: props.columns.length + (props.selectable ? 1 : 0) }, props.empty || 'No hay resultados')])])])]) } })
const props = defineProps({ show: Boolean, otNumber: String })
defineEmits(['close'])
const tabs = [{ id: 'actividades', label: 'Actividades' }, { id: 'base', label: 'Base Instalada' }, { id: 'historial', label: 'Historial del domicilio' }, { id: 'materiales', label: 'Materiales' }, { id: 'siniestros', label: 'Siniestros' }]
const activeTab = ref('actividades'), isExpanded = ref(false), showSubgrilla = ref(false), selectedHistorial = ref(null), showValidateConfirm = ref(false), showMaterialsAlert = ref(false), showSaveAlert = ref(false)
const pos = ref({ x: 60, y: 60 }), isDragging = ref(false); let startX = 0, startY = 0, initialX = 0, initialY = 0
const actividadesCols = [{ field: 'cod', label: 'COD ACTIVIDAD' }, { field: 'actividad', label: 'ACTIVIDAD' }, { field: 'cantidad', label: 'CANTIDAD' }, { field: 'cmo', label: 'COD CMO' }, { field: 'descCmo', label: 'CMO' }]
const baseCols = [{ field: 'base', label: 'BASE INSTALADA' }, { field: 'modelo', label: 'MODELO' }, { field: 'serie', label: 'NRO SERIE' }]
const materialCols = [{ field: 'cod', label: 'COD MATERIAL' }, { field: 'desc', label: 'DESC MATERIAL' }, { field: 'cantidad', label: 'CANTIDAD' }, { field: 'accion', label: 'ACCION' }, { field: 'estado', label: 'ESTADO' }, { field: 'validado', label: 'MATERIAL VALIDADO' }]
const resultCols = [{ field: 'cod', label: 'COD ACTIVIDAD' }, { field: 'actividad', label: 'ACTIVIDAD' }, { field: 'cantidad', label: 'CANTIDAD' }, { field: 'cmo', label: 'COD CMO' }, { field: 'descCmo', label: 'CMO' }, { field: 'regla', label: 'REGLA TIPO' }, { field: 'aplicada', label: 'REGLA APLICADA' }, { field: 'motivo', label: 'MOTIVO' }, { field: 'estado', label: 'ESTADO ACTIVO' }, { field: 'validada', label: 'VALIDADA' }, { field: 'accion', label: 'ACCION' }]
const actividades = ref([{ cod: '1285', actividad: 'Instalar Acometida HFC', cantidad: '1', cmo: '5021497', descCmo: 'INSTALACION DE ACOMETIDA DOMICILIARIA' }, { cod: '90014', actividad: 'Se instaló CM Internet y Telefonía', cantidad: '1', cmo: '0000001', descCmo: 'NO HAY CMO' }, { cod: '90000', actividad: 'Se instaló acometida', cantidad: '1', cmo: '0000001', descCmo: 'NO HAY CMO' }])
const baseInstalada = ref([]), materiales = ref([])
const historial = ref([{ ot: 'M00966068', creacion: '2026-06-10 17:10:02.0', cierre: '2026-06-13 12:04:01.0', acta: 'A2732', estado: 'Certificada', contra: 'NET AND WORK S.A.', red: 'N', actividades: [{ codigo: '1285', desc: 'Instalar Acometida HFC', cant: '1', ncnd: 'ND1045', est_ncnd: 'En Curso', est_act: 'S' }] }, { ot: 'M00981724', creacion: '2026-06-13 12:53:40.0', cierre: '2026-06-13 14:23:58.0', acta: 'A2732', estado: 'Certificada', contra: 'NET AND WORK S.A.', red: 'N', actividades: [{ codigo: '90014', desc: 'Se instaló CM Internet y Telefonía', cant: '1', ncnd: '', est_ncnd: '', est_act: 'N' }] }])
const resultantes = ref([{ selected: false, cod: '70501', actividad: 'ACOMETIDA SOLO INT', cantidad: '1', cmo: '5021495', descCmo: 'INST.D/ACOMETIDA HFC', regla: 'E3', aplicada: 'E3IX00001AR-70501', motivo: 'APLICACION DE REGLAS', estado: 'S', validada: 'N', accion: '' }, { selected: false, cod: '70502', actividad: 'VALIDACION ACOMETIDA', cantidad: '1', cmo: '5021496', descCmo: 'VALIDACION TECNICA HFC', regla: 'E4', aplicada: 'E4IX00001AR-70502', motivo: 'VALIDACION AUTOMATICA', estado: 'S', validada: 'N', accion: '' }])
const siniestro = ref({ nroEhs: '', nroOi: '' })
const consultarMateriales = () => { materiales.value = []; showMaterialsAlert.value = true }
const limpiarSiniestro = () => { siniestro.value = { nroEhs: '', nroOi: '' } }
const guardarSiniestro = () => { showSaveAlert.value = true }
const openHistorial = (hist) => { selectedHistorial.value = hist; showSubgrilla.value = true }
const exportHistorial = () => downloadExcel({ filename: 'historial_domicilio.xls', title: 'Historial domicilio', columns: [{ field: 'ot', label: 'NRO OT' }, { field: 'creacion', label: 'FECHA CREACION OT' }, { field: 'cierre', label: 'FECHA CIERRE' }, { field: 'acta', label: 'NRO ACTA' }, { field: 'estado', label: 'ESTADO ACTA' }, { field: 'contra', label: 'EMPRESA CONTRATISTA' }, { field: 'red', label: 'OT RED' }], rows: historial.value })
const confirmValidate = () => { showValidateConfirm.value = false; showSaveAlert.value = true }
const center = () => { pos.value = { x: Math.max((window.innerWidth - 1100) / 2, 12), y: Math.max((window.innerHeight - 650) / 2, 12) } }
const toggleExpand = () => { isExpanded.value = !isExpanded.value }
const startDrag = (e) => { if (isExpanded.value) return; isDragging.value = true; startX = e.clientX; startY = e.clientY; initialX = pos.value.x; initialY = pos.value.y; document.addEventListener('mousemove', onDrag); document.addEventListener('mouseup', stopDrag) }
const onDrag = (e) => { if (!isDragging.value) return; pos.value.x = initialX + e.clientX - startX; pos.value.y = initialY + e.clientY - startY }
const stopDrag = () => { isDragging.value = false; document.removeEventListener('mousemove', onDrag); document.removeEventListener('mouseup', stopDrag) }
watch(() => props.show, (value) => { if (value) { center(); activeTab.value = 'actividades'; isExpanded.value = false } })
</script>

<style scoped>
.ot-note-popup { width: 1100px; height: 650px; max-width: 96vw; max-height: 92vh; }.ot-header { background: #fff; color: #00a9bd; border-bottom: 1px solid #eceff1; cursor: grab; }.popup-controls { display: flex; gap: 12px; color: #b0bec5; cursor: pointer; }.ot-body { background: #fafafa; padding: 15px; overflow: auto; }.ot-info { display: grid; grid-template-columns: 1.2fr 1.6fr 1.2fr 1.2fr 1.2fr; gap: 14px; background: #fff; padding: 10px; border: 1px solid #eceff1; }.ot-info label { display: block; font-weight: 700; margin-bottom: 5px; }.ot-info input, .siniestros-box input { width: 100%; height: 30px; border: 1px solid #bdbdbd; border-radius: 3px; padding: 4px 8px; background: #e9e9e9; }.ot-tabs { display: flex; background: #f1f3f4; margin-top: 10px; overflow-x: auto; }.ot-tabs button { min-width: 150px; border: 0; background: transparent; padding: 12px; color: #00a9bd; cursor: pointer; }.ot-tabs button.active { background: #fff; color: #455a64; border-top: 3px solid #00bcd4; }.tab-box, .resultantes { background: #fff; border: 1px solid #eceff1; padding: 12px; }.section-title { display: flex; justify-content: space-between; align-items: center; gap: 10px; }.table-wrap { overflow: auto; border: 1px solid #d1d1d1; min-height: 125px; max-height: 210px; }.fm-grid { width: max-content; min-width: 100%; border-collapse: collapse; }.fm-grid th, .fm-grid td { border-right: 1px solid #c9c9c9; border-bottom: 1px solid #c9c9c9; padding: 8px; white-space: nowrap; }.fm-grid th { background: #f7f7f7; font-weight: 600; }.fm-grid tr.selected td { background: #e0f7fa; }.empty-row { text-align: center; color: #607d8b; padding: 25px; }.arrow-btn { border: 0; background: transparent; cursor: pointer; }.ot-link { color: #00a9bd; font-weight: 800; }.check-col { width: 38px; text-align: center; }.siniestros-box { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; max-width: 780px; margin: 30px auto; }.siniestros-actions { grid-column: 1 / -1; display: flex; justify-content: center; gap: 14px; }.popup-actions { display: flex; justify-content: flex-end; gap: 10px; padding: 12px 18px; background: #fff; }.btn-cyan, .btn-cyan-outline { border-radius: 18px; padding: 8px 18px; font-weight: 800; cursor: pointer; }.btn-cyan { background: #00a9bd; border: 1px solid #00a9bd; color: #fff; }.btn-cyan-outline { background: #fff; border: 1px solid #00a9bd; color: #00a9bd; }@media (max-width: 900px) { .ot-info, .siniestros-box { grid-template-columns: repeat(2, minmax(180px, 1fr)); } .popup-actions, .section-title { flex-direction: column; align-items: stretch; } }@media (max-width: 560px) { .ot-info, .siniestros-box { grid-template-columns: 1fr; } .btn-cyan, .btn-cyan-outline { width: 100%; } }
</style>
